name: mimic-fhir
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - sqlalchemy
  - seaborn
  - pandas
  - psycopg2
  - matplotlib
  - pytest
  - psycopg2
  - jupyter
  - requests
  - tqdm
  - yapf
  - google-cloud-storage
  - google-cloud-logging
  - google-cloud-bigquery
  - google-cloud-pubsub
  - google-api-python-client
  - google-auth
  - pip
  - pip:
    - python-dotenv
    - fhir.resources
    - pandas-gbq
